modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Theoman9402/FreeHands/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Theoman9402/FreeHands"
authors="Theoman02"
logoFile="freehands.png"
description='''
Adds a keybind to quickly move the item in your hand or offhand back into your inventory.
Supports main-hand/offhand-first preference and an option to ignore the hotbar when stashing.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
